USE [master]
GO
/****** Object:  Database [RealEstateDB]    Script Date: 4/20/2021 5:24:56 AM ******/
CREATE DATABASE [RealEstateDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RealEstateDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\RealEstateDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'RealEstateDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\RealEstateDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [RealEstateDB] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RealEstateDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [RealEstateDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [RealEstateDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [RealEstateDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [RealEstateDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [RealEstateDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [RealEstateDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [RealEstateDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [RealEstateDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [RealEstateDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [RealEstateDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [RealEstateDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [RealEstateDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [RealEstateDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [RealEstateDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [RealEstateDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [RealEstateDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [RealEstateDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [RealEstateDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [RealEstateDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [RealEstateDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [RealEstateDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [RealEstateDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [RealEstateDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [RealEstateDB] SET  MULTI_USER 
GO
ALTER DATABASE [RealEstateDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [RealEstateDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [RealEstateDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [RealEstateDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [RealEstateDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [RealEstateDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [RealEstateDB] SET QUERY_STORE = OFF
GO
USE [RealEstateDB]
GO
/****** Object:  Table [dbo].[Owner]    Script Date: 4/20/2021 5:24:56 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Owner](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CreatedDate] [date] NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Email] [nvarchar](50) NOT NULL,
	[Tel] [numeric](10, 0) NOT NULL,
 CONSTRAINT [PK_Owner] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [IX_Owner] UNIQUE NONCLUSTERED 
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Property]    Script Date: 4/20/2021 5:24:56 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Property](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CreatedDate] [date] NOT NULL,
	[Reference] [nvarchar](10) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Price] [float] NOT NULL,
	[Description] [nvarchar](max) NULL,
	[OwnerId] [int] NOT NULL,
 CONSTRAINT [PK_Property] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [IX_Property] UNIQUE NONCLUSTERED 
(
	[Reference] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[Owner] ADD  CONSTRAINT [DF_Owner_CreatedDate]  DEFAULT (getdate()) FOR [CreatedDate]
GO
ALTER TABLE [dbo].[Property] ADD  CONSTRAINT [DF_Property_CreatedDate]  DEFAULT (getdate()) FOR [CreatedDate]
GO
ALTER TABLE [dbo].[Property]  WITH CHECK ADD  CONSTRAINT [FK_Property_Owner] FOREIGN KEY([OwnerId])
REFERENCES [dbo].[Owner] ([Id])
GO
ALTER TABLE [dbo].[Property] CHECK CONSTRAINT [FK_Property_Owner]
GO
USE [master]
GO
ALTER DATABASE [RealEstateDB] SET  READ_WRITE 
GO
